### ISSUE TITLE
Additional features

### ISSUE THREAD

**Issue by flynfish** [phallstrom/slackistrano#22]
What do you think about adding support for the image_url field so we can have an image in the message?

![screen shot 2015-05-29 at 4 34 21 pm](https://cloud.githubusercontent.com/assets/253936/7893944/98b576d8-0620-11e5-946c-ce17f1ee5c5c.png)

It would also be cool to support the author params. 

![screen shot 2015-05-29 at 4 32 30 pm](https://cloud.githubusercontent.com/assets/253936/7893935/7970ba6c-0620-11e5-86e8-8165c0b4be5d.png)

Let me know what you think, if you don't have time I could work on a PR.

**Comment by phallstrom** [comment]
I don't know if I would use it, but I'm not opposed to it if people want to add it in as an option.  The author stuff might be interesting too.  Happy to look at a PR.

**Comment by bradgreens** [comment]
I like the idea of supporting author params instead of plucking `:slack_deploy_user` - which, I think comes from the current terminal user doing the deploy?

**Comment by phallstrom** [comment]
I'm currently rewriting things to support any and all formatting you want to spend the time implementing by letting you specify a "messaging class" that you then override whatever methods necessary to send what you want. Not quite done, but it Mostly Works™ right now. See the `overhaul` branch.

My thought is if folks come up with interesting/useful classes we can throw them and a screenshot into an examples directory, for others to re-use.

**Comment by phallstrom** [comment]
3.1.0.beta just went to rubygems. Should be 100% backward compatible. Also includes info on how to customize to your heart's content. https://github.com/phallstrom/slackistrano#customizing-the-messaging
