### ISSUE TITLE
Slackbot HTTP 404 Not Found

### ISSUE THREAD

**Issue by seankibler** [phallstrom/slackistrano#36]
When using slackbot integration the HTTP POST returns a 404.

My configuration of slackbot in `config/deploy.rb` looks like this:

```
set :slack_via_slackbot, true                                                                                         
set :slack_team, "actual team name"                                                                                         
set :slack_token, "a real token"                                                         
set :slack_channel, '#mx-deploy'                                                                                      
set :slack_username, 'mxdeploybot'
```

I run `cap dev deploy` and no message posts in slack. I run `cap -t dev deploy` and I can see the `slack:deploy:updating` task runs. 

I run `cap dev slack:deploy:updating` and get no message in slack.

I go to gem source and assign `Slackistrano.post(...)` to a var and puts that var, it is HTTPNotFound class.

Looking at the Slackbot doc it seems like it uses websockets and I don't see any websockets implementation in `slackistrano/slackistrano.rb`. I assume this was an API change that happened after you wrote the slackbot integration in Slackistrano.

If my assumption is correct would you accept a PR removing the slackbot integration or documenting it as broken? I would be happy to do the legwork on that. Otherwise, if my assumption is incorrect, please advise.

**Comment by phallstrom** [comment]
I haven't used this option in awhile, nor will have time to investigate in for the next several days. Happy to have you look into it and/or post more information here.

**Comment by phallstrom** [comment]
@seankibler Still haven't gotten around to this. If you can provide more info or a PR that would be great. Or just links to the docs. I no longer use slackistrano daily so it doesn't get the attention it deserves I'm afraid.

**Comment by seankibler** [comment]
I plan to at least investigate more and I would really like to put some dev in and make a PR. I do have a 5 month old at home though so we'll see how that goes. Thanks for at least keeping tabs on this.

**Comment by phallstrom** [comment]
@seankibler Congrats!

**Comment by seankibler** [comment]
Here is the announcement of the Real Time Messaging API. http://slackhq.com/post/104688116560/rtm-api

Of course the integration is far more complex now but I suspect some people would still find it valuable given RTM bot users are free. Glad to hear your thoughts since I'm willing to take a shot at implementation, but I could be persuaded that my investment would be in vain.

**Comment by phallstrom** [comment]
Asshole neighbors? Install a loud speaker on that side of the house hooked up to your baby monitor 😈

So, I just did a test using slackbot and it's working for me.  My config:

```
set :slack_via_slackbot, true
set :slack_team, "myteam"
set :slack_token, "xxxxxx"
set :slack_channel, '#slackistrano'
```

I setup the Slack configuration here: https://slack.com/apps/A0F81R8ET-slackbot

Can you let me know if that page doesn't work for you? Maybe it's a grandfathered thing, but it is working for me right now.

**Comment by seankibler** [comment]
That page exists for me. I added that app integration to our team and configured it and It worked. I was trying with the wrong integration app using the "Bots" and not "Slackbot". My apologies, I didn't realize that existed, should have looked harder.

**Comment by seankibler** [comment]
Closing. Thanks!

Oh thanks for the baby monitor tip lol, although I'm taking the high road with those people. They are the "nothing to lose" type of people. Neighbor wars with people like them are always in vain. We planned on moving anyway, looking for something more rural. I'll miss good Internet but its worth it for my daughter to grow up in a safer place without Meth people drinking on their roof and people burning tires.

**Comment by seankibler** [comment]
Closing. Thanks!

Oh thanks for the baby monitor tip lol, although I'm taking the high road with those people. They are the "nothing to lose" type of people. Neighbor wars with people like them are always in vain. We planned on moving anyway, looking for something more rural. I'll miss good Internet but its worth it for my daughter to grow up in a safer place without Meth people drinking on their roof and people burning tires.

**Comment by phallstrom** [comment]
I think Bots is pretty new, an agree it's kind of confusing :/

Good luck with the rural/kiddo/life!
