### ISSUE TITLE
#{fetch :slack_deploy_or_rollback} is always empty?

### ISSUE THREAD

**Issue by alanhartless** [phallstrom/slackistrano#45]
For some reason, #{fetch :slack_deploy_or_rollback} is always empty resulting in a message like `alan has failed to  branch master of theApp`. I have a custom message for the stage like 

```
set :slack_msg_failed,         -> { "#{fetch :slack_deploy_user} has failed to #{fetch :slack_deploy_or_rollback} branch #{fetch :branch} of #{fetch :application}" }
```

Any thoughts?

**Comment by phallstrom** [comment]
Strange. Can you run the following two commands and attach the payload output (if it's truncated on screen, check log/capistrano.log):

```
cap --dry-run slack:deploy:updating
cap --dry-run slack:deploy:failed
```

Then remove your custom message and re-run to see if it's still missing. Thanks!

**Comment by phallstrom** [comment]
Feel free to re-open if this is still an issue.
