### ISSUE TITLE
Integration image is broken

### ISSUE THREAD

**Issue by seanlinsley** [phallstrom/slackistrano#49]
<img width="378" alt="screen shot 2016-05-02 at 11 08 03 am" src="https://cloud.githubusercontent.com/assets/688886/14959704/36600b88-1056-11e6-961c-03b86be84184.png">

**Comment by seanlinsley** [comment]
Before today it was working fine.

**Comment by phallstrom** [comment]
Version 3.0.1 pushed to rubygems. Thx!

**Comment by seanlinsley** [comment]
Thanks for fixing it so quickly 😄
