### ISSUE TITLE
How can I change icon_url and username?

### ISSUE THREAD

**Issue by nashirox** [phallstrom/slackistrano#56]
I'm using `3.1.0.beta` and customizing some messages.
Additionally, I want to change icon url and username. so set some option like `set :slack_icon_url` in `config/deploy.rb` but not working.

Do i need to override helper methods?
Is it correct way?

https://github.com/phallstrom/slackistrano/blob/ffe8f433f2ca48ba63dce3d9b821e09a8fa72e42/lib/slackistrano/messaging/helpers.rb#L6

any message is helpful. thanks in advance.

**Comment by phallstrom** [comment]
You'll want to override the method in your own custom class per https://github.com/phallstrom/slackistrano/tree/ffe8f433f2ca48ba63dce3d9b821e09a8fa72e42#customizing-the-messaging
