### ISSUE TITLE
How can I set custom slack_username

### ISSUE THREAD

**Issue by Medesko** [phallstrom/slackistrano#61]
Hi @phallstrom,

Thank You for this amazing Job! 

How can I set custom slack_username and slack_icon_url ?

**Comment by phallstrom** [comment]
You need to define your own custom messaging class per

https://github.com/phallstrom/slackistrano#customizing-the-messaging

with a class something like this:

```
module Slackistrano
  class CustomMessaging < Messaging::Base
     def icon_url
        'http://some.site/path/to/image.png'
      end

      def username
        'Medesko'
      end
  end
end
```
