### ISSUE TITLE
slack_deploy_user deprecated ?

### ISSUE THREAD

**Issue by JochenFromm** [phallstrom/slackistrano#64]
A recent [commit](https://github.com/phallstrom/slackistrano/commit/0eff9f168cc1dfa75243bb734bcd2bc74794010a) seems to indicate that the parameter `slack_deploy_user`is now deprecated. Is this correct? Then this code which was previously recommended to set custom fields probably no longer works as well, what would be the right format?

```
set :slack_fields_updated,
   [
     {
       title: "Project",
       value: "<https://github.com/XXXXX/#{fetch(:application)}|#{fetch(:application)}>",
       short: true
     },
     {
       title: "Environment",
       value: fetch(:stage),
       short: true
     },
     {
       title: "Deployer",
       value: fetch(:slack_deploy_user),
       short: true
     },
     {
       title: "Revision",
       value: "<https://github.com/XXXXX/#{fetch(:application)}/commit/#{fetch(:slack_revision)}|#{fetch(:slack_revision)[0..6]}>",
       short: true
     }
   ]
```

**Comment by phallstrom** [comment]
You'll want to modify what you've got into the new way documented here: https://github.com/phallstrom/slackistrano#customizing-the-messaging

You can start with the DeprecatedMessaging class if you want to build from that, but might be easier to just start over.  Note this requires the new version of the gem.
