### ISSUE TITLE
Change hook for deploy:finishing/'slack:deploy:updated'

### ISSUE THREAD

**Issue by gonace** [phallstrom/slackistrano#72]
It would be great if I could overwrite these hooks, we have a lot of stuff going on after the actual deploy and need to change when 'slack:deploy:updated' should be triggered.

Regards,
Erik

**Comment by phallstrom** [comment]
Interesting. I wonder if you could use anything mentioned here https://stackoverflow.com/questions/22712240/remove-hook-from-flow-in-capistrano-3 to remove the hook and re-add it later.  I'm not sure how else I could make that easily configurable. ENV vars maybe but that's yucky. Let me know if you have any ideas.

**Comment by gonace** [comment]
Hi
I the problem we're having is that Slackistrano runns before som "post deployment" steps so it could result in slackistrano posting a "Success" then a "Failed" after :)

I'll have a look at what you've recommend, I think that will suffice 👍
