### ISSUE TITLE
Can't send messages using Slack Bot

### ISSUE THREAD

**Issue by PedroBrochado** [phallstrom/slackistrano#73]
Everywhere I look I don't find where to get the Slackbot token. All I get is [this[(https://api.slack.com/methods/chat.postMessage)
If I use a bot token on the configuration token value I keep getting 404s.

Is the Slackbot feature working?

**Comment by phallstrom** [comment]
@PedroBrochado Sorry for the delay...

Looks like they are trying to discourage it. I can easily find it in one of my teams (very old) but not one of the new ones.  However, looks like you can still go directly to it.

https://<YOURTEAMHERE>.slack.com/apps/A0F81R8ET-slackbot

Try that and let me know if it works and I can update the README.
