### ISSUE TITLE
How can I get a list of all servers 

### ISSUE THREAD

**Issue by ilijamt** [phallstrom/slackistrano#76]
Is it possible to get a list of all the servers I'm deploying too, so my message will show to which servers I'm also deploying.

![screenshot from 2017-09-06 18-08-54](https://user-images.githubusercontent.com/1139427/30122513-fa180074-932e-11e7-8880-7c0ce92ec6bb.png)

**Comment by PiTrem** [comment]
you could define some helper method in your custom_messaging.rb
```
      def server_hostnames
        roles(:web).map do |host|
          "#{host.user}@#{host.hostname}"
        end.join(', ')
      end

      def payload_for_updating
        {
          text: "on server #{server_hostnames} " + super[:text]
        }
      end
```
