### ISSUE TITLE
fyi, recipe for including github compare URL in updated message

### ISSUE THREAD

**Issue by jrochkind** [phallstrom/slackistrano#77]
Just putting this here so people will find it googling or searching issues.

If your repo is hosted on github, and you'd like the updated slack message to include a link to the github "compare" diff showing what's changed in the new release, just put this in your custom messaging class:

~~~
    def payload_for_updated
      current = fetch(:current_revision)
      previous = fetch(:previous_revision)

      super.tap do |payload|
        if current && previous
          payload[:attachments] ||= []
          payload[:attachments] << {
              title: "Github Diff",
              title_link: "https://github.com/YOUR_ORG/YOUR_PROJ/compare/#{CGI.escape previous}...#{CGI.escape current}",
              short: false
            }
        end
      end
    end
~~~

**Comment by phallstrom** [comment]
Neat. I've started up a wiki and put this in there. If you'd like to be the author feel free to re-add it and I'll remove mine.

https://github.com/phallstrom/slackistrano/wiki/Recipe-for-including-github-compare-URL-in-updated-message
