### ISSUE TITLE
OpenSSL error

### ISSUE THREAD

**Issue by JoshNorthrup** [phallstrom/slackistrano#79]
I'm getting the following:
```
WARN  [slackistrano] Error notifying Slack!
WARN  [slackistrano]   Error: #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed>
```
Rails 5.0.6
Ruby 2.3.3

config/deploy.rb:
```
set :slackistrano, {
    channel: '#channelname',
    webhook: url'
}
```
I can `curl` a message from the server I'm deploying to without any issues.

**Comment by charlyrodri** [comment]
Hi Josh,

I know it's been a long time but could you tell me how you solved this issue?

Thanks,
