### ISSUE TITLE
Slack API Failure! when calling payload_for_failed from CustomMessaging

### ISSUE THREAD

**Issue by Mosab-Mohamed** [phallstrom/slackistrano#80]
payload_for_failed gives this error:
`[slackistrano] Slack API Failure!
[slackistrano]   URI: https://hooks.slack.com/services/
[slackistrano]   Code: 404
[slackistrano]   Message: Not Found
[slackistrano]   Body: channel_not_found
`

and this error gone when i make payload_for_failed returns nil

**Comment by phallstrom** [comment]
Sorry for the delay @Mosab-Mohamed.  Is this still an issue for you? What's the rest of your configuration look like?
