### ISSUE TITLE
Not sending notifications when we have Puma + Nginx as webserver 

### ISSUE THREAD

**Issue by chetanbothra** [phallstrom/slackistrano#81]
Hi Team,

Using this for a while now. Thanks for this amazing tool. I got a strange issue, Please mark it as close if irrelevant.

I was using this tool on RoR application with Thin as the web server with Nginx on Ubuntu and it works fine, Lately, we started using Puma with Nginx on Ubuntu and see that no notifications were sent to slack channel. I Made sure my configurations are same as I was using with Thin. 

With Nginx + Thin
OS-  Ubuntu 14/16
Nginx version: nginx/1.4.6 (Ubuntu) 
Thin Version -  1.6
Ruby Version - ruby-2.3.0
Rails Version - 5 

With Nginx + Puma
OS-  Ubuntu 14/16
Nginx version: nginx/1.4.6 (Ubuntu)
Puma Version - 3.4
Ruby Version - ruby-2.4.1
Rails Version - 5

Please let me know if you need anything else

**Comment by phallstrom** [comment]
Sorry for the delay @chetanbothra...  I can't think of how slackistrano would be affected by your choice of webserver.  Slackistrano does it's thing as part of the deploy.  Shouldn't even matter if you have a web server installed.

Is this still an issue?
