### ISSUE TITLE
Allow changing of message via config

### ISSUE THREAD

**Issue by ruudk** [phallstrom/slackistrano#85]
Older versions of Slackistrano allowed me to easily change the payload_for_updating message. In the latest version you have to create a new .rb file to extend a certain class. That's not really convenient for newbies like me. 

Any plans on making this easier?

**Comment by phallstrom** [comment]
Sorry, but nope. Intentionally went the other way as the number of options and bits to twiddle kept expanding. There's an example in the README that will get you where you need to go though.
