### ISSUE TITLE
Restrict the slack notification in staging and development

### ISSUE THREAD

**Issue by raviskit** [phallstrom/slackistrano#86]
Hi,

I used this gem and now its posting notifications for every deployment in any environments or using any branch.
I want a hook which allows it to post notifications if a production deployment happens and disable it for development and staging environment.
I tried using 
`set :slackistrano, false if Rails.env == 'staging'` but its giving error as Rails is not available.

Please address this issue.

Thank you

**Comment by phallstrom** [comment]
You can disable specific environments by setting `set :slackistrano, false` in that environments deploy configuration (ie. `deploy/staging.yml`). 

See: https://github.com/phallstrom/slackistrano#disabling-posting-to-slack
