### ISSUE TITLE
Logic for Default Webhook Chanel is incorrect

### ISSUE THREAD

**Issue by arianf** [phallstrom/slackistrano#90]
https://github.com/phallstrom/slackistrano/blob/00c63ca9927935cbaa518102ae45e88e158029c5/lib/slackistrano/capistrano.rb#L56

If using slack bot is `true` this will `!(true) == false` is true, which is the wrong behavior.

Should just be 

```ruby
if @messaging.via_slackbot? == false && channels.empty?
```

**Comment by phallstrom** [comment]
@arianf 3.8.4 is on rubygems. thanks!
